openapi: 3.0.0
servers:
  - url: 'http://example.io/v2'
info:
  description: >-
    API description.
  version: 1.0.0
  title: Yacta OpenAPI
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Info
    description: Everything about info in general
paths:
  /info:
    get:
      tags:
        - Info
      description: ''
      operationId: getInfo
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
        '405':
          description: Invalid input

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    Info:
      title: Info
      description: Informations
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ApiResponse:
      title: ApiResponse
      description: Describes the result of uploading an image resource
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
          
