openapi: 3.0.0
info:
  description: API description.
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Yacta OpenAPI
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://example.io/v2
tags:
- description: Everything about info in general
  name: Info
paths:
  /info:
    get:
      description: ""
      operationId: getInfo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
          description: successful operation
        "405":
          description: Invalid input
      tags:
      - Info
components:
  schemas:
    Info:
      description: Informations
      example:
        name: name
        id: 0
      properties:
        id:
          format: int64
          title: id
          type: integer
        name:
          title: name
          type: string
      required:
      - name
      title: Info
      type: object
    ApiResponse:
      description: Describes the result of uploading an image resource
      properties:
        code:
          format: int32
          type: integer
        type:
          type: string
        message:
          type: string
      title: ApiResponse
      type: object
