# coding: utf-8

"""
    Yacta OpenAPI

    API description.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.info_api import router as InfoApiRouter

app = FastAPI(
    title="Yacta OpenAPI",
    description="API description.",
    version="1.0.0",
)

app.include_router(InfoApiRouter)
